### PR TITLE
chore: fix linter errors

### PR DESCRIPTION
**Pull request by wemeetagain**
Not sure how the linter was updated without introducing linter errors, but somehow it happened.
Fix all linter errors

### CODE REVIEW

**Comment by maschad** [comment]
Yah that's a bit strange because [the pr](https://github.com/ChainSafe/js-libp2p-yamux/pull/20/commits/81812b5dacf9c479d23fcc17ceaaa7c5c11867d0) that upgraded `aegir` to `38.1.0` [passed](https://github.com/ChainSafe/js-libp2p-yamux/actions/runs/3910460444/jobs/6682688696#step:5:12)

Also looks like you missed [a few errors](https://github.com/ChainSafe/js-libp2p-yamux/actions/runs/4620866010/jobs/8171563423?pr=31#step:5:10) @wemeetagain

**Review by dapplion — APPROVED** [review]

**Review by maschad — CHANGES_REQUESTED** [review]
We shouldn't need to include the  `package-lock.json`

**Comment by dapplion** [comment]
> We shouldn't need to include the `package-lock.json`

Yes not in this PR but I think all libp2p repos should commit a lock file (either yarn or npm) to ensure consistent DX

**Comment by achingbrain** [comment]
The breaking linting rules were accidentally included in `eslint-config-ipfs@3.1.6` and then reverted shortly afterwards in `eslint-config-ipfs@3.1.7` and then re-released as `eslint-config-ipfs@4.0.0` - sorry about that.

Master of this repo lints fine right now, this PR isn't strictly necessary at the moment though something like it may be required after the next aegir version.

**Pull request closed without merging**
